# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    
const playerNum = Math.floor((Math.random() * 11) + 1);
const playerNumTwo = Math.floor((Math.random() * 11) + 1);
const comNum = Math.floor((Math.random() * 11) + 1);


const blackJack = {
	const playerCardOne = playerNum;
	const playerCardTwo = playerNumTwo;
	
	const comCardOne = comNum;
	const comCardTwo = comNum;
    let playerHand = playerCardOne + playerCardTwo;
	let comHand = comCardOne + comCardTwo;
	let comCardTotal = comCardOne + comCardTwo;
    let playerCardTotal = playerCardOne + playerCardTwo;

	let showPlayerHand = (playerCardOne + ', ' + playerCardTwo);
    let showComHand = (comCardOne + ', ' + comCardTwo);

console.log(showPlayerHand);
console.log(playerCardTotal);
console.log(showComHand);
console.log(comCardTotal);
};
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
